# Domain-specific configuration for FiQA
data:
  query_file: "data/retrieval_tasks/fiqa/fiqa_questions.jsonl"
  qrels_file: "data/retrieval_tasks/fiqa/qrels/dev.tsv"
  corpus_path: "data/passage_level_processed/fiqa"

retrieval:
  index_name: "fiqa_sparse"
  index_path: "indices/fiqa/dense"
